<?php
/**
 * This file is automatically created by Recurly's OpenAPI generation process
 * and thus any edits you make by hand will be lost. If you wish to make a
 * change to this file, please create a Github issue explaining the changes you
 * need and we will usher them to the appropriate places.
 */
namespace Recurly\Resources;

use Recurly\RecurlyResource;

// phpcs:disable
class SubscriptionChangeBillingInfo extends RecurlyResource
{
    private $_three_d_secure_action_result_token_id;

    protected static $array_hints = [
    ];

    
    /**
    * Getter method for the three_d_secure_action_result_token_id attribute.
    * A token generated by Recurly.js after completing a 3-D Secure device fingerprinting or authentication challenge.
    *
    * @return ?string
    */
    public function getThreeDSecureActionResultTokenId(): ?string
    {
        return $this->_three_d_secure_action_result_token_id;
    }

    /**
    * Setter method for the three_d_secure_action_result_token_id attribute.
    *
    * @param string $three_d_secure_action_result_token_id
    *
    * @return void
    */
    public function setThreeDSecureActionResultTokenId(string $three_d_secure_action_result_token_id): void
    {
        $this->_three_d_secure_action_result_token_id = $three_d_secure_action_result_token_id;
    }
}