#!/usr/bin/env bash
set -e

function check_for_command {
  if ! hash eval "$1" 2>/dev/null; then
    echo "✖ Could not find '$1'" 
    exit 1
  fi
  echo "✓ Found $1"
}

check_for_command "php"
check_for_command "composer"
